// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjLpN-mwZkJT9Opu4lo4ixqqPdQTZBbxQ',
    appId: '1:1006901437819:web:ee401ec81e2bd1ccdc09de',
    messagingSenderId: '1006901437819',
    projectId: 'plant-shop-app-3',
    authDomain: 'plant-shop-app-3.firebaseapp.com',
    storageBucket: 'plant-shop-app-3.appspot.com',
    measurementId: 'G-71NY3XF9QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfDlkpG2cpbyWmGUeqkTeEdndpgM9nt_o',
    appId: '1:1006901437819:android:133efe9643d97aa2dc09de',
    messagingSenderId: '1006901437819',
    projectId: 'plant-shop-app-3',
    storageBucket: 'plant-shop-app-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjetZe2dt-Y9LRv0XzIvz72GD7PklvzrE',
    appId: '1:1006901437819:ios:cb902a24fee34243dc09de',
    messagingSenderId: '1006901437819',
    projectId: 'plant-shop-app-3',
    storageBucket: 'plant-shop-app-3.appspot.com',
    iosClientId: '1006901437819-kg69g8dkg4lvte7s5bdv50ckenpm1cfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjetZe2dt-Y9LRv0XzIvz72GD7PklvzrE',
    appId: '1:1006901437819:ios:cb902a24fee34243dc09de',
    messagingSenderId: '1006901437819',
    projectId: 'plant-shop-app-3',
    storageBucket: 'plant-shop-app-3.appspot.com',
    iosClientId: '1006901437819-kg69g8dkg4lvte7s5bdv50ckenpm1cfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantShopApp',
  );
}
